### ISSUE TITLE
does the result better than 2 stage?

### ISSUE THREAD

**Issue by jinfagang** [choiHkk/VAEJETS#1]
does the result better than 2 stage?

**Comment by choiHkk** [comment]
I think 2 stage tts system is much better than this yet.

**Comment by jinfagang** [comment]
how about compare with vits

**Comment by choiHkk** [comment]
But I didn't use "blank token" in CTC Loss(alignment learning). Besides model and training parameters didnt' optimized. 
I think it can get better quality with some technics like "blank token" and loss coefficient for stft loss (or l1 loss)
